spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
debug: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG

