version: "3.8"

services:
  config-server:
    image: config-server
    build: .
    restart: always
    ports:
      - "8888:8888"
    networks:
      - smartpos-network
  eureka-server:
    image: eureka-server
    build: .
    restart: always
