server:
  port: 8060  # API Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # enable dynamic routing from Eureka
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
      

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: true
