name: Build and Deploy Angular Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-pos-frontend
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Check working directory
      - name: Check working directory
        run: |
          ls
          pwd

      # 3️⃣ Docker Login
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4️⃣ Build and push Docker image
      - name: Build and push Docker image
        env:
          DOCKER_REPO: kamhassan/smartpos-angular
          BASE_TAG: latest
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_TAG="${BASE_TAG}-${SHORT_SHA}"

          echo "Building Docker image with tag: $DOCKER_REPO:$IMAGE_TAG"
          docker build -t $DOCKER_REPO:$IMAGE_TAG .

          echo "Pushing image to Docker Hub..."
          docker push $DOCKER_REPO:$IMAGE_TAG

          echo "::notice::Docker image pushed: $DOCKER_REPO:$IMAGE_TAG"
